import pyautogui
import time
pyautogui.hotkey("win", "d")
time.sleep(1)
pyautogui.typewrite("brave-browser")
time.sleep(1)
pyautogui.press("enter")
time.sleep(20)
pyautogui.typewrite("web.whatsapp.com")
pyautogui.press("enter")
time.sleep(20)
pyautogui.press("tab")
time.sleep(0.7)
pyautogui.press("tab")
time.sleep(0.7)
pyautogui.press("tab")
time.sleep(0.7)
pyautogui.press("tab")
time.sleep(0.7)
pyautogui.press("tab")
time.sleep(0.7)
pyautogui.press("tab")
time.sleep(0.7)
pyautogui.press("tab")
time.sleep(0.7)
pyautogui.press("tab")
time.sleep(0.7)
pyautogui.press("tab")

pyautogui.typewrite("olaamortoyprobando")
pyautogui.press("enter")
